### ISSUE TITLE
关于新的抽卡模型的可能性

### ISSUE THREAD

**Issue by FourFeaves** [OneBST/GI_gacha_dataset#3]
可能会不会有一种新的抽卡的模型？我有一个思路，但是并不确定

**Comment by OneBST** [comment]
如果你是从做游戏的角度来看，那可选择的模型有很多，大可以提出新的实现方法。
不过如果是从解释原神抽卡系统的角度来看，目前的模型已经很好了，能解释所有现象而且很简洁。
你有想法不妨分享出来讨论。

**Comment by FourFeaves** [comment]
可以私聊吗？

**Comment by FourFeaves** [comment]
q 1850390672

**Comment by OneBST** [comment]
加了
